### ISSUE TITLE
Add PolyToken support on Mainnet

### ISSUE THREAD

**Issue by kotaru77** [PolymathNetwork/polymath.js#16]
Currently polymath-core doesn't contain address of the PolyToken which is 0x9992ec3cf6a55b00978cddf2b27bc6882d88d1ec and for PolyToken.js we use PolyTokenFaucet.json. So we need to replace PolyTokenFaucet.json with PolyToken.json, but keep Faucet ABI to support getTokens() function on testnets and add PolyToken address to it for mainnet network.

**Comment by PolymathTeam** [comment]
➤ Matthew Woo commented:

[Boris Shevchenko](https://app.asana.com/0/528285401193323/list) just to clarify we need to complete this task in order launch on Mainnet to allow issuers to pay in Poly for different transactions right?

**Comment by PolymathTeam** [comment]
➤ Thomas Borrel commented:

Included in v1.3.0

**Comment by PolymathTeam** [comment]
➤ Boris Shevchenko commented:

Leave this task in To Test for me for a while

**Comment by PolymathTeam** [comment]
➤ Boris Shevchenko commented:

[Matthew Woo](https://app.asana.com/0/461575372520165/list) no, for testnets we use PolyTokenFaucet contract, but for mainnet we must use PolyToken contract
